webPortal/app/chatbot/models.py
class FeedbackSurvey():
    def __init__(self,survey_name,questions,item_count):
        self.__item_count = item_count
        self.__questions=questions
        self.__survey_name=survey_name

    @property
    def item_count(self):
        return self.__item_count

    @property
    def questions(self):
        return self.__questions

    @property
    def survey_name(self):
        return self.__survey_name

webPortal/app/chatbot/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField
from wtforms.validators import DataRequired

class SurveyForm(FlaskForm):
    name = StringField("Name", validators=[DataRequired()])
    submit = SubmitField("Submit")

class QuestionForm(FlaskForm):
    text = StringField("Text", validators=[DataRequired()])
    submit = SubmitField("Submit")

class SurveyCompleteForm(FlaskForm):
    existingQuestionId=IntegerField("existingQuestionId")
    newQuestion=StringField("newQuestion", validators=[DataRequired()])
    surveyId=IntegerField("surveyId", validators=[DataRequired()])

webPortal/app/chatbot/routes.py
from flask import Blueprint, render_template, request,redirect,url_for,session, jsonify,make_response
from flask_babel import gettext, get_locale
from flask_login import login_required
from .forms import SurveyForm,QuestionForm,SurveyCompleteForm
from app.models import ChatbotFeedbackSurvey,ChatbotFeedbackQuestion,ChatbotFeedbackResponse
from app import db

import json
import requests


chatbot = Blueprint("chatbot", __name__)

@chatbot.route("/api/getsurveyform")
def get_surveyform():
    response=make_response()
   

    chatbotsurvey=ChatbotFeedbackSurvey.query.filter_by(active=True).first()
    if chatbotsurvey:
        result=db.session.query(ChatbotFeedbackSurvey, ChatbotFeedbackQuestion).filter(ChatbotFeedbackSurvey.id == ChatbotFeedbackQuestion.survey_id).filter_by(active=True).order_by(ChatbotFeedbackQuestion.order).all()
        itemLst=[]
        for item in result:
            itemLst.append(item.ChatbotFeedbackQuestion.serialize_content())

        response=jsonify(items=itemLst)
    
    response=jsonify(items=itemLst)
    response.headers.add("Access-Control-Allow-Origin", "*")
    return response


    return jsonify(items=None)
#@chatbot.route("/chatbot")
#def view_chatbot():
#    return render_template("chatbot.html",headerText=gettext("Chatbot feature"))

@chatbot.route("/dashboard/chatbot/chatbotgraph")
@login_required
def view_chatbot_graph():
    return render_template("chatbot/chatbot_graph.html",headerText=gettext("Chatbot Graph"))

@chatbot.route("/dashboard/chatbot/updatequestionslist",methods=["POST"])
@login_required
def update_questions_list():
    form=SurveyCompleteForm()
    survey=ChatbotFeedbackSurvey.query.get(form.surveyId.data)

    if survey:
        for key in request.form.keys():
            if "btnNewQuestion" in key:
                question=ChatbotFeedbackQuestion()
                question.text=form.newQuestion.data
                question.order=survey.questions.count()+1
                survey.questions.append(question)
                db.session.commit()
                break
            elif "btnDelete" in key:
                questionid=key.replace("btnDelete_","")
                questionToDel=ChatbotFeedbackQuestion.query.get(questionid)
                db.session.delete(questionToDel)
                db.session.commit()
                break

    availableQuestions=getAvailableQuestions(survey.questions)
    results=db.session.query(ChatbotFeedbackSurvey, ChatbotFeedbackQuestion).filter(
        ChatbotFeedbackSurvey.id==form.surveyId.data,ChatbotFeedbackSurvey.id == ChatbotFeedbackQuestion.survey_id).order_by(ChatbotFeedbackQuestion.order).all()

    return render_template("chatbot/manage_questions.html",headerText=gettext("Manage surveys"),survey=survey,questions=results,availableQuestions=availableQuestions)

def getAvailableQuestions(surveyQuestions):
    questions=ChatbotFeedbackQuestion.query.all()

  #TODO this is an horrible loop...outerjoin would be a much better solution 
    availableQuestions = []
    skip=False
    for question in questions:
        for squestion in surveyQuestions:
            if question.id==squestion.id:
                skip=True
                break

        if not skip:
            availableQuestions.append(question)
        skip=False

    return availableQuestions

@chatbot.route("/dashboard/chatbot/updatequestionorder/<int:surveyid>/<int:questionid>/<int:direction>")
@login_required
def update_question_order(surveyid,questionid,direction):
    survey=ChatbotFeedbackSurvey.query.get(surveyid)

    for row in survey.questions:
        if row.id==questionid:
            #find the question that has the target order no
            for trow in survey.questions:
                if trow.order==direction:
                    trow.order=row.order
                    row.order=direction
                    db.session.commit()
                    break
            break

    results=db.session.query(ChatbotFeedbackSurvey, ChatbotFeedbackQuestion).filter(
        ChatbotFeedbackSurvey.id == ChatbotFeedbackQuestion.survey_id,ChatbotFeedbackSurvey.id==surveyid).order_by(ChatbotFeedbackQuestion.order).all()

    availableQuestions=getAvailableQuestions(survey.questions)

    return render_template("chatbot/manage_questions.html",headerText=gettext("Manage surveys"),survey=survey,questions=results,availableQuestions=availableQuestions)

@chatbot.route("/dashboard/chatbot/managequestions/<int:surveyid>")
@login_required
def manage_questions(surveyid):

    survey=ChatbotFeedbackSurvey.query.get(surveyid)
    availableQuestions=getAvailableQuestions(survey.questions)

    results=db.session.query(ChatbotFeedbackSurvey, ChatbotFeedbackQuestion).filter(
        ChatbotFeedbackSurvey.id == ChatbotFeedbackQuestion.survey_id,ChatbotFeedbackSurvey.id==surveyid).order_by(ChatbotFeedbackQuestion.order).all()

    return render_template("chatbot/manage_questions.html",headerText=gettext("Manage surveys"),survey=survey,questions=results,availableQuestions=availableQuestions)

@chatbot.route("/dashboard/chatbot/managesurveys")
@login_required
def manage_surveys():
    surveys=ChatbotFeedbackSurvey.query.all()
    return render_template("chatbot/manage_surveys.html",headerText=gettext("Manage surveys"),surveys=surveys)

#TODO not secure at all
@chatbot.route("/dashboard/chatbot/activatesurvey/<int:id>",methods=["GET"])
@login_required
def activate_survey(id):
    survey=ChatbotFeedbackSurvey.query.filter_by(active=True).first()
    if survey:
        survey.active=False

    surveyToActivate=ChatbotFeedbackSurvey.query.get(id)
    surveyToActivate.active=True

    db.session.commit()
    return redirect(url_for("chatbot.manage_surveys"))
     
@chatbot.route("/dashboard/chatbot/addsurvey",methods=["GET","POST"])
@login_required
def add_survey():

    form=SurveyForm()
    if form.validate_on_submit():
        s = ChatbotFeedbackSurvey(name=form.name.data, active=False)
        db.session.add(s)
        db.session.commit()
        return redirect(url_for("chatbot.manage_surveys"))

    return render_template("chatbot/survey_form.html",headerText=gettext("Add a new survey"),form=form)

@chatbot.route("/dashboard/chatbot/deletesurvey",methods=["POST"])
@login_required
def delete_survey():

    for key in request.form.keys():
        if "delete" in key:
            surveyid=key.replace("delete_","")
            survey=ChatbotFeedbackSurvey.query.filter_by(id=surveyid).first()
            db.session.delete(survey)
            db.session.commit()

    return redirect(url_for('chatbot.manage_surveys'))

@chatbot.route("/dashboard/chatbot/updatesurvey/<int:id>", methods=["GET","POST"])
@login_required
def update_survey(id):
    
    survey = ChatbotFeedbackSurvey.query.get_or_404(id)
 
    form = SurveyForm()
    if form.validate_on_submit():
        survey.name = form.name.data
        db.session.commit()
        return redirect(url_for("chatbot.manage_surveys"))
    
    form.name.data=survey.name
    return render_template("chatbot/survey_form.html",headerText=gettext("Update survey"),form=form)

@chatbot.route("/dashboard/chatbot/updatequestion/<int:id>", methods=["GET","POST"])
@login_required
def update_question(id):
    question = ChatbotFeedbackQuestion.query.get_or_404(id)
    
    form = QuestionForm()
    if form.validate_on_submit():
        question.text = form.text.data
        db.session.commit()
        return redirect(url_for("chatbot.manage_surveys"))
    
    form.text=question.text
    return render_template("chatbot/manage_question.html",headerText=gettext("Update question"),form=form)

@chatbot.route("/dashboard/chatbot/managesurveyresponses/<int:surveyid>", methods=["GET"])
@login_required
def manage_survey_responses(surveyid):
    survey=ChatbotFeedbackSurvey.query.get_or_404(surveyid)
    return render_template("chatbot/manage_survey_responses.html",headerText=gettext("Manage responses"),survey=survey)

@chatbot.route("/dashboard/chatbot/viewsurveyresponse/<int:responseid>", methods=["GET"])
@login_required
def get_survey_response(responseid):
    r=ChatbotFeedbackResponse.query.get_or_404(responseid)
    response = make_response(r.response, 200)
    response.mimetype = "text/plain"
    return response

@chatbot.route("/chat")
def chat_chatbot():
    user_message = request.args["message"]
    lang = get_locale().language
    try:
        response = requests.get("http://chatbot:5005/"+lang+"/question/"+user_message)
        return response.text
    except:
        return gettext("Sorry, I seem to be asleep right now. Please try again later")

@chatbot.route("/questions")
def get_chatbot_questions():
    lang = get_locale().language
    try:
        response = requests.get("http://chatbot:5005/"+lang+"/questions")
        return response.text
    except:
        return gettext("Sorry, I seem to be asleep right now. Please try again later")

@chatbot.route("/delete_message", methods=["POST"])
def delete_chatbot_message():
    user_message = request.form["message_id"]
    try:
        response = requests.post("http://chatbot:5005/deleteChatMessage", data={"message_id" : user_message})
        return response.text, response.status_code
    except:
        return gettext("Sorry, I seem to be asleep right now. Please try again later")

@chatbot.route("/add_message", methods=["POST"])
def add_chatbot_message():
    question_message = request.form["question_id"]
    new_message_en = request.form["add_text_en"]
    new_message_fr = request.form["add_text_fr"]
    try:
        response = requests.post("http://chatbot:5005/addChatMessage", data={"question_id" : question_message, "new_message_en" : new_message_en, "new_message_fr" : new_message_fr})
        return response.text, response.status_code
    except:
        return gettext("Sorry, I seem to be asleep right now. Please try again later")


@chatbot.route("/chatbot/submitfeedbacksurvey", methods=["POST"])
def submit_feedback_survey():
    #get the survey id

webPortal/app/templates/chatbot/chatbot_graph.html
{% extends "admin/layout.html" %}
{% block javascripthead %}
<script src="{{ url_for('static', filename='js/mxClient.min.js') }}"></script>
{% endblock javascripthead %}
{% block javascript %}
<script>
    function main(){
        $.ajax({
            url:"{{ url_for('chatbot.get_chatbot_questions') }}",
            method: "GET",
            success: function(result){
                let response = JSON.parse(result);
                createGraph(document.getElementById('graphContainer'), response.questions, response.answers);
            }
        })
    }

    function createGraph(container, questions, answers){
        if(!mxClient.isBrowserSupported()){
            mxUtils.error("Browser not supported!", 200, false);
        }else{
            mxEvent.disableContextMenu(container);
            //create graph
            var graph = new mxGraph(container);
            var parent = graph.getDefaultParent();

            //update graph to add in vertices and edges
            graph.getModel().beginUpdate();
            var question_map = {};
            var answer_map = {};

            var style = graph.getStylesheet().getDefaultVertexStyle();
            style[mxConstants.STYLE_FONTSIZE] = 22;
            try{
                questions.forEach(q => {
                    var g1 = graph.insertVertex(parent, "message_"+q.id, q.message, 20, 20, 80, 30);
                    graph.updateCellSize(g1, true);
                    question_map[q.id]=g1;
                    answer_map[q.id]=g1;
                    g1.setAttribute("test123", );
                    if(q.user_response != null){
                        g1.setStyle("fillColor=yellow");
                    }
                });
                
                answers.forEach(a =>{
                    graph.insertEdge(parent, null, '', answer_map[a.question_id], question_map[a.answer_id]);
                });
            } finally{
                graph.getModel().endUpdate();
            }

            //update graph layout for the output to look like a dialog tree
            var layout = new mxCompactTreeLayout(graph);
            layout.horizontal = false;
            layout.execute(parent);

            //center the graph in the display
            var graphBounds = graph.getGraphBounds();
            $("#graphContainer").css("width", 100+graphBounds.width);
            $("#graphContainer").css("height", 100+graphBounds.height);
            graph.getModel().setGeometry(parent, new mxGeometry(100, 0, 100+graphBounds.width, 100+graphBounds.height));

            graph.addListener(mxEvent.CLICK, function(sender, evt){
                var cell = evt.getProperty('cell');
                console.log(cell);
                if(cell != null){
                    if(cell.vertex){
                        let message_id = cell.id.substring(8);

                        $("#btn-delete").unbind("click");
                        $("#btn-delete").on("click", function(){
                            graph.getModel().beginUpdate();
                            $.ajax({
                                url:"{{ url_for('chatbot.delete_chatbot_message') }}",
                                data: {message_id: message_id},
                                method: "POST",
                                success: function(result){
                                    graph.removeCells([cell]);
                                },
                                error: function(jqXHR){
                                    console.log(jqXHR);
                                }
                            });
                            graph.getModel().endUpdate();
                        });
                        $("#btn-delete").css("display", "block");

                        $("#btn-add").unbind("click");
                        $("#btn-add").on("click", function(){
                            let new_message_val_en = $("#add-input-en").val();
                            let new_message_val_fr = $("#add-input-fr").val();
                            if(new_message_val_en.trim() !== "" && new_message_val_fr.trim() !== ""){
                                $.ajax({
                                    url:"{{ url_for('chatbot.add_chatbot_message') }}",
                                    data: {question_id: message_id, add_text_en: new_message_val_en, add_text_fr: new_message_val_fr},
                                    method: "POST",
                                    success: function(result){
                                        $("#add-input-en").val('');
                                        $("#add-input-fr").val('');

                                        graph.getModel().beginUpdate();
                                        var g1 = graph.insertVertex(parent, "message_"+result, new_message_val, 20, 20, 80, 30)
                                        graph.updateCellSize(g1, true);
                                        if(cell.style !== "fillColor=yellow"){
                                            g1.setStyle("fillColor=yellow");
                                        }
                                        graph.insertEdge(parent, null, '', cell, g1);
                                        layout.execute(parent);
                                        graph.getModel().setGeometry(parent, new mxGeometry(100, 0, graphBounds.width, graphBounds.height));
                                        graph.getModel().endUpdate();
                                    },
                                    error: function(jqXHR){
                                        console.log(jqXHR);
                                    }
                                });
                            }
                        });
                        $("#div-add").css("display", "block");
                    }else{
                        $("#div-add").css("display", "none");
                        $("#btn-delete").css("display", "none");
                    }
                }
            });
        }
    }
</script>
{% endblock javascript %}

{% block content %}
{% include 'partials/title.html' %}

<body onload="main()">
    <div id="graphContainer" style="position: relative; overflow: auto; cursor: default; border-style: solid;"></div>
    <div id="div-add" style="display: none;">
        <button id="btn-add">{{ _("Add") }}</button>
        <input id="add-input-en" type="text" placeholder="Write the new question/answer here">
        <input id="add-input-fr" type="text" placeholder="Écriver votre nouvelle question/réponse ici">
        
    </div>
    <button id="btn-delete" style="display: none;">{{ _("Remove") }}</button>
</body>
{% endblock content %}

webPortal/app/templates/chatbot/manage_questions.html
{% extends "admin/layout.html" %}
{% block javascript %}
<script src="{{url_for('static', filename='js/bootstrap-select.min.js')}}"></script>
{% endblock %}
{% block content %}
{% include 'partials/title.html' %}
<div class="text-left" style="padding-top:2em;padding-bottom:2em">
<span>Survey name: </span>{{survey.name}}
</div>

<form method="POST" action="/dashboard/chatbot/updatequestionslist">
<!-- Project Card Example -->
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary">Add a brand new question</h6>
  </div>
  <div class="card-body">
      <div class="form-group">
        <input type="text" id="newQuestion" name="newQuestion" class="form-control" />
      </div>
      <div>
      <input type="submit" id="btnNewQuestion" name="btnNewQuestion" class="btn btn-primary" value="Add" />
    </div>
  </div>
</div>
<input type="hidden" id="surveyId" name="surveyId" value="{{survey.id}}"/>

<table class="table">
    <thead>
      <tr>
        <th scope="col">Text</th>
        <th scope="col">Change order</th>
        <th scope="col">Operation</th>
      </tr>
    </thead>
    <tbody>
    {% for row in questions %}
        <tr>
            <td>
                {{ row.ChatbotFeedbackQuestion.text }}
            </td>
            <td>
              {{ row.ChatbotFeedbackQuestion.order }}
              {% if row.ChatbotFeedbackQuestion.order > 1 %}
                <a href="{{ url_for('chatbot.update_question_order',surveyid=survey.id ,questionid=row.ChatbotFeedbackQuestion.id,direction=(row.ChatbotFeedbackQuestion.order-1)) }}" class="fa fa-lg fa-angle-up"></a>
              {% endif %}
              {% if row.ChatbotFeedbackQuestion.order < survey.questions.count() %}
                <a href="{{ url_for('chatbot.update_question_order',surveyid=survey.id ,questionid=row.ChatbotFeedbackQuestion.id,direction=(row.ChatbotFeedbackQuestion.order+1)) }}" class="fa fa-lg fa-angle-down"></a>
              {% endif %}


          </td>
            <td>
               
                <a class="btn btn-primary" href="{{ url_for('chatbot.update_question', id=row.ChatbotFeedbackQuestion.id) }}">Update text</a>
                <input type="submit" class="btn btn-danger" name="btnDelete_{{row.ChatbotFeedbackQuestion.id}}" value="Delete" />
                
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
</form>
{% endblock content %}

webPortal/app/templates/chatbot/manage_survey_responses.html
{% extends "admin/layout.html" %}
{% block javascript %}
<script>
$(document).ready(function(){

  $(".response").click(function(evt){
    evt.preventDefault();
    $("#responseContent").text("");
    var responseid=$(this).attr('id');
    $.ajax({
      url: '/dashboard/chatbot/viewsurveyresponse/' + responseid,
      type: 'get',
      success: function( data, textStatus, jQxhr ){
        var tmpData = JSON.parse(data);
        $("#responseContent").text(JSON.stringify(tmpData, null, '\t'));
        $("#responseDialog").modal();
      },
      error: function( jqXhr, textStatus, errorThrown ){
          console.log( errorThrown );
      }
    });
  });

});
</script>
{% endblock %}
{% block content %}
{% include 'partials/title.html' %}
<table class="table">
    <thead>
      <tr>
        <th scope="col">Id</th>
        <th scope="col">Operation</th>
      </tr>
    </thead>
    <tbody>
    {% for response in survey.responses %}
        <tr>
            <td>
                {{ response.id }}
            </td>
            <td>
                <a class="btn btn-primary response" id="{{response.id}}" href="/">View response content</a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
<a href="{{url_for('chatbot.manage_surveys')}}">Go back</a>

<div class="modal" id="responseDialog" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Response content</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p id="responseContent"></p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

webPortal/app/templates/chatbot/manage_surveys.html
{% extends "admin/layout.html" %}

{% block content %}
{% include 'partials/title.html' %}
<div class="text-left" style="padding-top:2em;padding-bottom:2em">
<a href="{{ url_for('chatbot.add_survey') }}" class="btn btn-primary">Add a new survey</a>
</div>
<form method="POST" action="{{url_for('chatbot.delete_survey')}}">
<table class="table">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Active?</th>
        <th scope="col">Operation</th>
      </tr>
    </thead>
    <tbody>
    {% for survey in surveys %}
        <tr>
            <td>
                {{ survey.name }}
            </td>
            <td>
                {% if not survey.active %}
                <a class="btn btn-primary" href="{{ url_for('chatbot.activate_survey', id=survey.id) }}">Activate</a>
                {% else %}

                {{ survey.active }}
                {% endif %}
            </td>
            <td>
                    <a class="btn btn-primary" href="{{ url_for('chatbot.manage_survey_responses', surveyid=survey.id)}}">View responses</a>
                    <a class="btn btn-primary" href="{{ url_for('chatbot.update_survey', id=survey.id) }}">Modify</a>
                    <a class="btn btn-primary" href="{{ url_for('chatbot.manage_questions', surveyid=survey.id) }}">Manage questions</a>
                   
                    <input type="submit" class="btn btn-danger" name="delete_{{survey.id}}" value="Delete"  />
                
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
</form>
{% endblock content %}

webPortal/app/templates/chatbot/survey_form.html
{% extends "admin/layout.html" %}

{% block content %}
{% include 'partials/title.html' %}
<div class="row">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.name.label }}
            {{ form.name(class_="form-control") }}
        </div>
        <div>
            {{ form.submit(class="btn btn-primary") }}
        </div>
    </form>
</div>
{% endblock content %}