webPortal/app/highlights/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired

class HightlightForm(FlaskForm):
    title = StringField("title", validators=[DataRequired()])
    image = FileField("Image", validators=[FileAllowed(["png", "jpg"])])
    description = StringField("description", validators=[DataRequired()])
    link = StringField("link", validators=[DataRequired()])
    submit = SubmitField("Submit")

webPortal/app/admin/routes.py
from sqlalchemy.sql import func
from flask import Blueprint, render_template, redirect, url_for,request,flash
from app import db
from app.admin.forms import LoginForm
from app.models import User
from flask_login import current_user, login_user,login_required,logout_user


admin = Blueprint("admin", __name__)


@admin.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('admin.dashboard'))
    form = LoginForm()

    if form.validate_on_submit():
     
        user = User.query.filter(
            func.lower(User.username) == func.lower(form.username.data)
        ).first()
        if user is None or not user.check_password(form.password.data):
            form = LoginForm()
            flash('Invalid login. Please try again.','error')
        else:
            login_user(user)
            return redirect(url_for('admin.dashboard'))


    return render_template("admin/login.html",form=form)

@admin.route('/dashboard/chatbot')
@login_required
def dashboardchatbot():
    return render_template('admin/dashboard.html')

@admin.route('/dashboard')
@login_required
def dashboard():
    return render_template('admin/dashboard.html')

@admin.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You are now logged out. See you again!')
    form = LoginForm()
    return render_template('admin/login.html',form=form)

webPortal/app/chatbot/routes.py
from flask import Blueprint, render_template, request,redirect,url_for,session, jsonify,make_response
from flask_babel import gettext, get_locale
from flask_login import login_required
from .forms import SurveyForm,QuestionForm,SurveyCompleteForm
from app.models import ChatbotFeedbackSurvey,ChatbotFeedbackQuestion,ChatbotFeedbackResponse
from app import db

import json
import requests


chatbot = Blueprint("chatbot", __name__)

@chatbot.route("/api/getsurveyform")
def get_surveyform():
    response=make_response()
   

    chatbotsurvey=ChatbotFeedbackSurvey.query.filter_by(active=True).first()
    if chatbotsurvey:
        result=db.session.query(ChatbotFeedbackSurvey, ChatbotFeedbackQuestion).filter(ChatbotFeedbackSurvey.id == ChatbotFeedbackQuestion.survey_id).filter_by(active=True).order_by(ChatbotFeedbackQuestion.order).all()
        itemLst=[]
        for item in result:
            itemLst.append(item.ChatbotFeedbackQuestion.serialize_content())

        response=jsonify(items=itemLst)
    
    response=jsonify(items=itemLst)
    response.headers.add("Access-Control-Allow-Origin", "*")
    return response


    return jsonify(items=None)
#@chatbot.route("/chatbot")
#def view_chatbot():
#    return render_template("chatbot.html",headerText=gettext("Chatbot feature"))

@chatbot.route("/dashboard/chatbot/chatbotgraph")
@login_required
def view_chatbot_graph():
    return render_template("chatbot/chatbot_graph.html",headerText=gettext("Chatbot Graph"))

@chatbot.route("/dashboard/chatbot/updatequestionslist",methods=["POST"])
@login_required
def update_questions_list():
    form=SurveyCompleteForm()
    survey=ChatbotFeedbackSurvey.query.get(form.surveyId.data)

    if survey:
        for key in request.form.keys():
            if "btnNewQuestion" in key:
                question=ChatbotFeedbackQuestion()
                question.text=form.newQuestion.data
                question.order=survey.questions.count()+1
                survey.questions.append(question)
                db.session.commit()
                break
            elif "btnDelete" in key:
                questionid=key.replace("btnDelete_","")
                questionToDel=ChatbotFeedbackQuestion.query.get(questionid)
                db.session.delete(questionToDel)
                db.session.commit()
                break

    availableQuestions=getAvailableQuestions(survey.questions)
    results=db.session.query(ChatbotFeedbackSurvey, ChatbotFeedbackQuestion).filter(
        ChatbotFeedbackSurvey.id==form.surveyId.data,ChatbotFeedbackSurvey.id == ChatbotFeedbackQuestion.survey_id).order_by(ChatbotFeedbackQuestion.order).all()

    return render_template("chatbot/manage_questions.html",headerText=gettext("Manage surveys"),survey=survey,questions=results,availableQuestions=availableQuestions)

def getAvailableQuestions(surveyQuestions):
    questions=ChatbotFeedbackQuestion.query.all()

  #TODO this is an horrible loop...outerjoin would be a much better solution 
    availableQuestions = []
    skip=False
    for question in questions:
        for squestion in surveyQuestions:
            if question.id==squestion.id:
                skip=True
                break

        if not skip:
            availableQuestions.append(question)
        skip=False

    return availableQuestions

@chatbot.route("/dashboard/chatbot/updatequestionorder/<int:surveyid>/<int:questionid>/<int:direction>")
@login_required
def update_question_order(surveyid,questionid,direction):
    survey=ChatbotFeedbackSurvey.query.get(surveyid)

    for row in survey.questions:
        if row.id==questionid:
            #find the question that has the target order no
            for trow in survey.questions:
                if trow.order==direction:
                    trow.order=row.order
                    row.order=direction
                    db.session.commit()
                    break
            break

    results=db.session.query(ChatbotFeedbackSurvey, ChatbotFeedbackQuestion).filter(
        ChatbotFeedbackSurvey.id == ChatbotFeedbackQuestion.survey_id,ChatbotFeedbackSurvey.id==surveyid).order_by(ChatbotFeedbackQuestion.order).all()

    availableQuestions=getAvailableQuestions(survey.questions)

    return render_template("chatbot/manage_questions.html",headerText=gettext("Manage surveys"),survey=survey,questions=results,availableQuestions=availableQuestions)

@chatbot.route("/dashboard/chatbot/managequestions/<int:surveyid>")
@login_required
def manage_questions(surveyid):

    survey=ChatbotFeedbackSurvey.query.get(surveyid)
    availableQuestions=getAvailableQuestions(survey.questions)

    results=db.session.query(ChatbotFeedbackSurvey, ChatbotFeedbackQuestion).filter(
        ChatbotFeedbackSurvey.id == ChatbotFeedbackQuestion.survey_id,ChatbotFeedbackSurvey.id==surveyid).order_by(ChatbotFeedbackQuestion.order).all()

    return render_template("chatbot/manage_questions.html",headerText=gettext("Manage surveys"),survey=survey,questions=results,availableQuestions=availableQuestions)

@chatbot.route("/dashboard/chatbot/managesurveys")
@login_required
def manage_surveys():
    surveys=ChatbotFeedbackSurvey.query.all()
    return render_template("chatbot/manage_surveys.html",headerText=gettext("Manage surveys"),surveys=surveys)

#TODO not secure at all
@chatbot.route("/dashboard/chatbot/activatesurvey/<int:id>",methods=["GET"])
@login_required
def activate_survey(id):
    survey=ChatbotFeedbackSurvey.query.filter_by(active=True).first()
    if survey:
        survey.active=False

    surveyToActivate=ChatbotFeedbackSurvey.query.get(id)
    surveyToActivate.active=True

    db.session.commit()
    return redirect(url_for("chatbot.manage_surveys"))
     
@chatbot.route("/dashboard/chatbot/addsurvey",methods=["GET","POST"])
@login_required
def add_survey():

    form=SurveyForm()
    if form.validate_on_submit():
        s = ChatbotFeedbackSurvey(name=form.name.data, active=False)
        db.session.add(s)
        db.session.commit()
        return redirect(url_for("chatbot.manage_surveys"))

    return render_template("chatbot/survey_form.html",headerText=gettext("Add a new survey"),form=form)

@chatbot.route("/dashboard/chatbot/deletesurvey",methods=["POST"])
@login_required
def delete_survey():

    for key in request.form.keys():
        if "delete" in key:
            surveyid=key.replace("delete_","")
            survey=ChatbotFeedbackSurvey.query.filter_by(id=surveyid).first()
            db.session.delete(survey)
            db.session.commit()

    return redirect(url_for('chatbot.manage_surveys'))

@chatbot.route("/dashboard/chatbot/updatesurvey/<int:id>", methods=["GET","POST"])
@login_required
def update_survey(id):
    
    survey = ChatbotFeedbackSurvey.query.get_or_404(id)
 
    form = SurveyForm()
    if form.validate_on_submit():
        survey.name = form.name.data
        db.session.commit()
        return redirect(url_for("chatbot.manage_surveys"))
    
    form.name.data=survey.name
    return render_template("chatbot/survey_form.html",headerText=gettext("Update survey"),form=form)

@chatbot.route("/dashboard/chatbot/updatequestion/<int:id>", methods=["GET","POST"])
@login_required
def update_question(id):
    question = ChatbotFeedbackQuestion.query.get_or_404(id)
    
    form = QuestionForm()
    if form.validate_on_submit():
        question.text = form.text.data
        db.session.commit()
        return redirect(url_for("chatbot.manage_surveys"))
    
    form.text=question.text
    return render_template("chatbot/manage_question.html",headerText=gettext("Update question"),form=form)

@chatbot.route("/dashboard/chatbot/managesurveyresponses/<int:surveyid>", methods=["GET"])
@login_required
def manage_survey_responses(surveyid):
    survey=ChatbotFeedbackSurvey.query.get_or_404(surveyid)
    return render_template("chatbot/manage_survey_responses.html",headerText=gettext("Manage responses"),survey=survey)

@chatbot.route("/dashboard/chatbot/viewsurveyresponse/<int:responseid>", methods=["GET"])
@login_required
def get_survey_response(responseid):
    r=ChatbotFeedbackResponse.query.get_or_404(responseid)
    response = make_response(r.response, 200)
    response.mimetype = "text/plain"
    return response

@chatbot.route("/chat")
def chat_chatbot():
    user_message = request.args["message"]
    lang = get_locale().language
    try:
        response = requests.get("http://chatbot:5005/"+lang+"/question/"+user_message)
        return response.text
    except:
        return gettext("Sorry, I seem to be asleep right now. Please try again later")

@chatbot.route("/questions")
def get_chatbot_questions():
    lang = get_locale().language
    try:
        response = requests.get("http://chatbot:5005/"+lang+"/questions")
        return response.text
    except:
        return gettext("Sorry, I seem to be asleep right now. Please try again later")

@chatbot.route("/delete_message", methods=["POST"])
def delete_chatbot_message():
    user_message = request.form["message_id"]
    try:
        response = requests.post("http://chatbot:5005/deleteChatMessage", data={"message_id" : user_message})
        return response.text, response.status_code
    except:
        return gettext("Sorry, I seem to be asleep right now. Please try again later")

@chatbot.route("/add_message", methods=["POST"])
def add_chatbot_message():
    question_message = request.form["question_id"]
    new_message_en = request.form["add_text_en"]
    new_message_fr = request.form["add_text_fr"]
    try:
        response = requests.post("http://chatbot:5005/addChatMessage", data={"question_id" : question_message, "new_message_en" : new_message_en, "new_message_fr" : new_message_fr})
        return response.text, response.status_code
    except:
        return gettext("Sorry, I seem to be asleep right now. Please try again later")


@chatbot.route("/chatbot/submitfeedbacksurvey", methods=["POST"])
def submit_feedback_survey():
    #get the survey id

webPortal/app/highlights/routes.py
from flask import Blueprint, render_template, redirect, url_for, current_app
from flask_babel import gettext
from app.models import Highlight
from app.highlights.forms import HightlightForm 
import os, secrets
from PIL import Image
from app import db
from flask_login import login_required

highlights = Blueprint("highlights", __name__)


@highlights.route("/dashboard/highlights")
@login_required
def view_highlights():
    highlights = Highlight.query.all()
    return render_template("highlights.html",headerText=gettext("Highlights"), highlights=highlights)


def save_image(form_image):
    random_hex = secrets.token_hex(8)
    _, f_ext = os.path.splitext(form_image.filename)
    image_filename = random_hex+f_ext
    image_path = os.path.join(current_app.root_path, "static/media/highlight_images", image_filename)

    output_size = (300, 300)
    i = Image.open(form_image)
    i.thumbnail(output_size)
    i.save(image_path)
    
    return image_filename


@highlights.route("/dashboard/new_highlight", methods=["GET", "POST"])
@login_required
def new_highlight():
    form = HightlightForm()
    if form.validate_on_submit():
        h = Highlight(title_en=form.title.data, description_en=form.description.data, link=form.link.data)
        if(form.image.data):
            image_filename = save_image(form.image.data)
            h.image = image_filename
        db.session.add(h)
        db.session.commit()
        return redirect(url_for("highlights.view_highlights"))

    return render_template("highlights_form.html", headerText = gettext("Add a new Highlight"), form=form)



@highlights.route("/dashboard/update_highlight/<int:highlight_id>", methods=["GET", "POST"])
@login_required
def update_highlight(highlight_id):
    highlight = Highlight.query.get_or_404(highlight_id)
    
    form = HightlightForm()
    if form.validate_on_submit():
        highlight.title_en = form.title.data
        highlight.description_en = form.description.data
        highlight.link = form.link.data
        if(form.image.data):
            image_filename = save_image(form.image.data)
            highlight.image = image_filename
        db.session.commit()
        return redirect(url_for("highlights.view_highlights"))
    
    form.title.data = highlight.title_en
    form.description.data = highlight.description_en
    form.link.data = highlight.link
    return render_template("highlights_form.html", headerText = gettext("Update the Highlight"), form=form)


@highlights.route("/dashboard/delete_highlight/<int:highlight_id>", methods=["POST"])
@login_required
def delete_highlight(highlight_id):
    highlight = Highlight.query.get_or_404(highlight_id)

    db.session.delete(highlight)
    db.session.commit()
    
    return redirect(url_for("highlights.view_highlights"))

webPortal/app/main/routes.py
from flask import Blueprint, render_template, send_from_directory, g
from flask_babel import gettext
from app import db
import requests
from app.models import ShinyReport,Highlight,User,ChatbotFeedbackSurvey,ChatbotFeedbackQuestion

main = Blueprint("main", __name__)

@main.route("/translate")
def translate():
    lang = g.lang_code
    if lang == "eng":
        return "fra"
    else:
        return "eng"

@main.route("/")
@main.route("/home")
def home():
    #TODO remove code duplication from highlight action :(
    highlights = Highlight.query.all()
    i = 0
    output = []
    templist = []
    for highlight in highlights:
        templist.append(highlight)
        i = i+1
        if i%3 == 0:
            output.append(templist)
            templist = []
    
    if templist!= []:
        output.append(templist)

    return render_template("intro.html", headerText=gettext("Weekly highlights"),highlights=highlights, output=output)


@main.route("/<path:path>", methods=["GET"])
def serve_static_content(path):
    return send_from_directory("static",path)


@main.route("/test_the_api")
def test_the_api():
    response = requests.get("http://test_api:5001/")

    return str(response.text)

webPortal/app/shiny/routes.py
from flask import Blueprint, render_template
from flask_babel import gettext
from app import db
from app.models import ShinyReport


shiny = Blueprint("shiny", __name__)


@shiny.route("/rshiny")
def view_rshiny():
    reports = ShinyReport.query.all()
    return render_template("rshiny.html", reports=reports, headerText=gettext("R-shiny feature"))

webPortal/app/templates/highlights.html
{% extends "admin/layout.html" %}

{% block javascripts %}
{% endblock javascripts %}

{% block content %}
{% include 'partials/title.html' %}
<div class="text-left" style="padding-top:2em;padding-bottom:2em">
<a href="{{ url_for('highlights.new_highlight') }}" class="btn btn-primary">{{ _("Add a new highlight") }}</a>
</div>
<table class="table">
    <thead>
      <tr>
        <th scope="col">{{ _("Title") }}</th>
        <th scope="col">{{ _("Description") }}</th>
        <th scope="col">{{ _("Link") }}</th>
        <th scope="col">{{ _("Image") }}</th>
        <th scope="col">{{ _("Operation") }}</th>
      </tr>
    </thead>
    <tbody>
    {% for highlight in highlights %}
        <tr>
            <td>
                {{ highlight.title }}
            </td>
            <td>
                {{ highlight.description }}
            </td>
            <td>
                <a class="nav-link" target="_blank" href="{{ highlight.link }}">{{ highlight.link }}</a>
            </td>
            <td>
                <img style="width:50%;" src="{{ url_for('static', filename='media/highlight_images/'+highlight.image) }}">
            </td>
            <td>
                <form method="POST" action="{{ url_for('highlights.delete_highlight', highlight_id=highlight.id) }}">
                    <a class="btn btn-primary" href="{{ url_for('highlights.update_highlight', highlight_id=highlight.id) }}">{{ _("Modify") }}</a>
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock content %}

webPortal/app/templates/highlights_form.html
{% extends "admin/layout.html" %}

{% block content %}
{% include 'partials/title.html' %}
<div>
    <form method="POST" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.title.label(class="form-control-label") }}
            {% if form.title.errors %}
                {{ form.title(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.title.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.title(class="form-control form-control-lg") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.image.label(class="form-control-label") }}
            {% if form.image.errors %}
                {{ form.image(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.image.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.image(class="form-control form-control-lg") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.description.label(class="form-control-label") }}
            {% if form.description.errors %}
                {{ form.description(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.description.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.description(class="form-control form-control-lg") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.link.label(class="form-control-label") }}
            {% if form.link.errors %}
                {{ form.link(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.link.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.link(class="form-control form-control-lg") }}
            {% endif %}
        </div>
        <div>
            {{ form.submit(class_="btn btn-primary") }}
        </div>
    </form>
</div>
<div class="row mt-4">
    <a href="{{url_for('highlights.view_highlights')}}" class="nav-link">{{ _("Return") }}</a>
</div>
{% endblock content %}

webPortal/app/templates/intro.html
{% extends "layout.html" %}

{% block header %}
<header>
  <div class="container-fluid" style="padding-top:1rem;padding-bottom:1rem;background: rgb(10, 100, 82);background: radial-gradient(circle, rgba(10,100,82) 0%, rgba(10,100,82) 35%, rgba(0,0,0,1) 100%);">
   <div class="container text-center">
     <i class="icon fas fa-cubes" style="font-size:16rem"></i>
     <h1 style="font-weight: 200;font-size:4rem">{{ _("Experimental portal") }}</h1>
     <p class="h4">{{ _("An experiment on Daaas potential features") }}</p>
   </div>
  </div>
</header>
{% endblock header %}

{% block content %}

{% include 'partials/title.html' %}
<div id="multi-item-example" class="carousel slide carousel-multi-item" data-ride="carousel">
  <div class="controls-top text-center">
      <a class="btn-floating" href="#multi-item-example" data-slide="prev">
        <i class="fas fa-chevron-left"></i>
      </a>
      <a class="btn-floating" href="#multi-item-example" data-slide="next">
          <i class="fas fa-chevron-right"></i>
      </a>
  </div>

  <div class="carousel-inner" role="listbox">
      {% for out in output %}
          <div class="carousel-item {{ 'active' if loop.index==1 }}">
              {% for highlight in out %}
                  <div class="col-md-4">
                      <div class="card mb-2">
                          <img class="card-img-top" src="{{ url_for('static', filename='media/highlight_images/'+highlight.image) }}">
                          <div class="highlight-container">
                              <h4 class="card-title">{{ highlight.title }}</h4>
                              <p class="card-text">{{ highlight.description }}</p>
                              <a class="btn btn-primary" href="{{ highlight.link }}" target="_blank">{{ _("Read more") }}</a>
                          </div>
                      </div>
                  </div>
              {% endfor %}
          </div>
      {% endfor %}
  </div>
  
  <ol class="carousel-indicators" style="position: static;">
      {% for out in output %}
          <li data-target="#multi-item-example" data-slide-to="{{loop.index-1}}" class="{{ 'active' if loop.index==1 }}"></li>
      {% endfor %}
  </ol>
</div>
{% endblock content %}

webPortal/app/templates/new_entry.html
{% extends "layout.html" %}

{% block content %}
{% include 'partials/title.html' %}
<div class="row">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.text.label }}
            {{ form.text(class="form-control") }}
        </div>
        <div>
            {{ form.submit(class="btn btn-primary") }}
        </div>
    </form>
</div>
{% endblock content %}

webPortal/app/templates/rshiny.html
{% extends "layout.html" %}
{% block javascripts %}
<script>
    $('#reports-list').change(function(){
        $("#div-iframe").css("display", "none");
        $("#load-spin").css("display", "block");
        let selected = $(this).children("option:selected");
        let title = selected.text();
        let location = selected.val();

        $("#div-iframe h2").text(title);
        $("#tag-iframe").attr("src", "http://localhost:3838/"+location+"/");
    })

    $("#tag-iframe").on("load", function(){
        $("#div-iframe").css("display", "block");
        $("#load-spin").css("display", "none");
    });  

    $('#reports-list').trigger("change");
</script>
{% endblock javascripts %}

{% block content %}
{% include 'partials/title.html' %}
<div class="mb-4">
    <h2>{{ _("Display r-shiny report in iframe. Click on a row to view the report.") }}</h2>
    <select id="reports-list">
        {% for report in reports %}
            <option value="{{report.location}}">
                {{report.title}}
            </option>
        {% endfor %}
    </select>
</div>

<div id="load-spin" style="display: none; height: 1000px; width: 1000px;">
    <div class="spinner-border text-light" role="status">
        <span class="sr-only">{{ _("Loading...") }}</span>
    </div>
</div>
<div id="div-iframe" style="display: none;">
    <h2></h2>
    <iframe id="tag-iframe"  width="1000" height="1000">
        <p>{{ _("Your browser does not support iframes.") }}</p>
    </iframe>
</div>
{% endblock content %}

webPortal/app/templates/todel_chatbot.html
{% extends "layout.html" %}

{% block javascripts %}
<script>
    function chat_call(chat, message){
        if(chat != ""){
            $("#chat-box").append("<p>USER: "+chat.innerText+"</p>")
        }

        $("#chat-answers").empty();
        $.ajax({
            url:"{{ url_for('chatbot.chat_chatbot') }}",
            method: "GET",
            data: {message : message},
            success: function(result){
                console.log(result);
                let response = JSON.parse(result);
                $("#chat-box").append("<p>BOT: "+response.answer.message+"</p>")
                response.questions.forEach(question => {
                    $("#chat-answers").append('<button class="btn btn-primary btn-answer" onclick="chat_call(this,'+question.id+')">'+question.message+'</button>&nbsp;')
                });
            }
        })
    }

    chat_call("",1);
</script>
{% endblock javascripts %}

{% block content %}
{% include 'partials/title.html' %}
<div style="border-style: solid;">
    <div id="chat-box">
    </div>
    <div id="chat-answers" class="mb-2">
    </div>
</div>
<div>
    <a class="btn btn-primary" href="{{ url_for('chatbot.view_chatbot_graph') }}">{{ _("View the chatbot script") }}</a>
</div>
{% endblock content %}

webPortal/app/templates/view_records.html
{% extends "layout.html" %}

{% block content %}
{% include 'partials/title.html' %}
<div class="row">
    <table class="table table-dark table-striped">
        <thead>
            <tr>
                <th>{{ _("id") }}</th>
                <th>{{ _("text") }}</th>
                <th>{{ _("Operations") }}</th>
            </tr>
        </thead>
        {% for entry in entries %}
            <tr>
                <td>{{entry.id}}</td>
                <td>{{entry.text}}</td>
                <td>
                    <a href="{{ url_for('records.update_post', entry_id=entry.id) }}" class="btn btn-primary">{{ _("Modify") }}</a>&nbsp;
                    <form method="POST" action="{{ url_for('records.delete_post', entry_id=entry.id) }}">
                        <input type="submit" class="btn btn-primary" value="Delete">
                    </form>
                </td>
            </tr>
        {% endfor %}
    </table>
</div>
<div class="row mt-4">
    <a href="{{url_for('records.new_entry')}}">{{ _("Add new entry") }}</a>
</div>
{% endblock content %}